# `version` is now deprecated
# https://docs.docker.com/compose/compose-file/#version-top-level-element

services:
  adventurers-app:
    container_name: adventurers-app
    build:
      context: ./adventurers-app
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./adventurers-app/src:/app/src
      - ./adventurers-app/public:/app/public
      # It's not necessary to sync the `.next` directory
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    networks:
      - my_network

  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/sites-enabled:/etc/nginx/sites-enabled
  #     - ./nginx/logs:/var/log/nginx
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - adventurers-app
  #   restart: always
  #   networks:
  #     - my_network

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: dev.Dockerfile
    environment:
      # The only variable required is `POSTGRES_PASSWORD`, the rest are optional
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    restart: always
    networks:
      - my_network
    ports:
      - 5432:5432

  # Add more containers below

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
